### DISCUSSION TITLE
Not able to login or register

### DISCUSSION THREAD

**Discussion by GentNiginz** [Zibbp/ganymede#107] [Q&A] [answered]
Hello everyone,

I managed to get Ganymede to run but I don't seem to be able to login or register.

Here is my docker-compose.yaml file:

```yaml
version: "3.3"
services:
  ganymede-api:
    container_name: ganymede-api
    image: ghcr.io/zibbp/ganymede:latest
    restart: unless-stopped
    environment:
      - TZ=Europe/Zurich
      - DB_HOST=ganymede-db
      - DB_PORT=5432
      - DB_USER=ganymede
      - DB_PASS=PASSWORD
      - DB_NAME=ganymede-prd
      - DB_SSL=disable
      - JWT_SECRET=SECRET
      - JWT_REFRESH_SECRET=SECRET
      - TWITCH_CLIENT_ID=<redacted>
      - TWITCH_CLIENT_SECRET=<redacted>
      - FRONTEND_HOST=http://<redacted>:4801
    volumes:
      - ./vods:/vods
      - ./logs:/logs
      - ./data:/data
    ports:
      - 4800:4000
  ganymede-frontend:
    container_name: ganymede-frontend
    image: ghcr.io/zibbp/ganymede-frontend:latest
    restart: unless-stopped
    environment:
      - API_URL=http://<redacted>:4800 # Points to the API service
      - CDN_URL=http://<redacted>:4802 # Points to the CDN service
      - SHOW_SSO_LOGIN_BUTTON=true # show/hide SSO login button on login page
      - FORCE_SSO_AUTH=false # force SSO auth for all users (bypasses login page and redirects to SSO)
      - REQUIRE_LOGIN=false # require login to view videos
    ports:
      - 4801:3000
  ganymede-db:
    container_name: ganymede-db
    image: postgres:14
    volumes:
      - ./ganymede-db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=PASSWORD
      - POSTGRES_USER=ganymede
      - POSTGRES_DB=ganymede-prd
    ports:
      - 4803:5432
  ganymede-nginx:
    container_name: ganymede-nginx
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./vods:/mnt/vods
    ports:
      - 4802:8080
```

Any help would be appriciated!
