### DISCUSSION TITLE
Deploying on Google Cloud Run

### DISCUSSION THREAD

**Discussion by benwa** [Zibbp/ganymede#748] [Q&A]
I am a beginner in containers, so please put on the kid gloves.

I am attempting to use Google Cloud Run to deploy Ganymede. The frontend runs as expected, but it seems that no environment variables are being passed to the container.

I keep seeing the following error in the log:
```log
anic: error getting config

goroutine 1 [running]:
github.com/rs/zerolog/log.Panic.(*Logger).Panic.func1({0x18339fc?, 0x0?})
	/go/pkg/mod/github.com/rs/zerolog@v1.34.0/log.go:405 +0x27
github.com/rs/zerolog.(*Event).msg(0xc0004893b0, {0x18339fc, 0x14})
	/go/pkg/mod/github.com/rs/zerolog@v1.34.0/event.go:158 +0x2aa
github.com/rs/zerolog.(*Event).Msg(...)
	/go/pkg/mod/github.com/rs/zerolog@v1.34.0/event.go:110
github.com/zibbp/ganymede/internal/server.SetupApplication({0x29c2a50, 0x35a8c80})
	/app/internal/server/server.go:64 +0x105
github.com/zibbp/ganymede/internal/server.Run({0x29c2a50, 0x35a8c80})
	/app/internal/server/server.go:183 +0x32
main.main()
	/app/cmd/server/main.go:23 +0x1f8
```

My scrubbed YAML:
```yaml
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  ...
spec:
  template:
    ...
    spec:
      ...
      containers:
      - name: ganymede-1
        image: REDACTED
        ports:
        - name: http1
          containerPort: 8080
        env:
        - name: DB_HOST
          value: REDACTED
        - name: DB_PORT
          value: '5432'
        - name: DB_USER
          value: REDACTED
        - name: DB_NAME
          value: REDACTED
        - name: TZ
          value: America/New_York
        - name: SHOW_LOCALE_BUTTON
          value: 'false'
        - name: TWITCH_CLIENT_ID
          value: REDACTED
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              key: latest
              name: DB_PASS
        - name: TWITCH_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              key: latest
              name: TWITCH_CLIENT_SECRET
        resources:
          ...
        volumeMounts:
        - name: ganymede-db-ssl
          mountPath: /data/db-ssl
        - name: ganymede-logs
          mountPath: /data/logs
        - name: ganymede-config
          mountPath: /data/config
        - name: ganymede-videos
          mountPath: /data/videos
        - name: ganymede-temp
          mountPath: /data/temp
        livenessProbe:
          ...
        startupProbe:
          ...
      volumes:
      - name: ganymede-db-ssl
        csi:
          driver: gcsfuse.run.googleapis.com
          readOnly: true
          volumeAttributes:
            bucketName: ganymede-db-ssl
      - name: ganymede-logs
        csi:
          driver: gcsfuse.run.googleapis.com
          volumeAttributes:
            bucketName: ganymede-logs
      - name: ganymede-config
        csi:
          driver: gcsfuse.run.googleapis.com
          volumeAttributes:
            bucketName: ganymede-config
      - name: ganymede-videos
        csi:
          driver: gcsfuse.run.googleapis.com
          volumeAttributes:
            bucketName: ganymede-videos
      - name: ganymede-temp
        emptyDir:
          medium: Memory
          sizeLimit: 32G
  traffic:
  ...
status:
  ...
```

Any ideas?
