### ISSUE TITLE
SSO: Invalid access token

### ISSUE THREAD

**Issue by TheBinaryLoop** [Zibbp/ganymede#136]
When using SSO as authentication source, it seems that the refresh token isn't used because after about an hour or so the webpage cant do anything that requires authentication anymore and every few seconds a red message appears that says that the access toke is invalid.

**Comment by Zibbp** [comment]
What provider are you using? If you open the browser console (ctrl + shift + i) and click application > cookies, do you see a refresh token there?

**Comment by TheBinaryLoop** [comment]
I use authentik. Yes i see a refresh token

**Comment by TheBinaryLoop** [comment]
Also, is there a logout button anywhere in the frontend or am I just missing it?

**Comment by Zibbp** [comment]
There is a logout button in Profile > Logout but I just noticed I never updated the code to remove oauth cookies. You'll have to open the browser console and delete the Ganymede cookies to fully logout.

I was able to recreate the refresh token issue with the `:latest` tag of Authentik. It appears Authentik is returning an invalid refresh toke (random characters that include . % $ which is invalid). I created a new Authentik instance using an older image tag [2023.1.2](https://github.com/goauthentik/authentik/pkgs/container/server/65146543?tag=2023.1.2) and it worked without issue. So there is something with the latest release, not sure when the bug was introduced between the `2023.1.2` and `latest` releases. What authentik version are you running? `:latest`? I don't see any issues raised upstream, I'll take a closer look this weekend.

If you want an immediate fix you'll need to deploy an older image that works. If you do want to revert to an older version for this to work. **DO NOT** use your current data, it did not work for me. I would make a new Authentik stack with new data folders.

**Comment by HaagridTV** [comment]
Without SSO:
Everything was working fine for a while, then suddenly I started getting this error.
```
Request Failed
Invalid access token
```
Looking at the network the `Invalid access token` is a 401 error from
`https://api.xxxx.com/api/v1/playback/last?limit=4`
Also see another 401 error from
`https://api.xxxx.com/api/v1/auth/refresh`
\
\
\
Then tried using SSO.
Off topic, have you tried using authelia for SSO. After loggin in I just get a
`{"message":"state cookie not found: http: named cookie not present"}`
from 
`https://api.xxxx.com/api/v1/auth/oauth/callback?code=authelia_ac_sNFSO....`
With all the ENV variables set according to the wiki.

**Comment by HaagridTV** [comment]
My `COOKIE_DOMAIN` was set to `vods.xxxx.com`.
Setting it to `xxxx.com` seems to resolve the issue.
Now I see `access-token` and `refresh-token` and login persists after refresh.
\
\
Only thing now is SSO using authelia, I'm getting some errors, from the API.
`{"message":"failed to exchange token: oauth2: cannot fetch token: 401 Unauthorized\nResponse: {\"error\":\"invalid_client\",\"error_description\":\"Client authentication failed (e.g., unknown client, no client authentication included, or unsupported authentication method).\"}"}`
\
And from the logs of Authelia I get.

`Access Request failed with error: Client authentication failed (e.g., unknown client, no client authentication included, or unsupported authentication method). the passwords don't match" method=POST path=/api/oidc/token remote_ip=x.x.x.x stack="github.com/authelia/authelia/v4/internal/handlers/handler_oidc_token.go:27.....(*workerPool).getCh.func1\nruntime/asm_amd64.s:1594 goexit"`
\
But that is an issue for tomorrow.
Solved the bigger issue.
Thanks.

**Comment by Zibbp** [comment]
One of the issues I noticed while trying to use Authelia, is that a `nickname` attribute isn't sent back. I modified the oauth login to fallback to `preferred_username` if a `nickname` is not available https://github.com/Zibbp/ganymede/commit/27818d84ff088e7864deb37dcf278ab577616d3c. I'm able to complete the entire oauth flow with Authelia but there is still another issue, Authelia is not returning a refresh token in the response. There's an access token but not refresh token. The refresh token grant is included in the config. I'm using the sort-of default config that Authelia provides. If you want to tinker with it more, the nickname fix is pushed to the `:main` tag.

```
identity_providers:
  oidc:
    hmac_secret: this_is_a_secret_abc123abc123abc
    issuer_private_key: |
      -----BEGIN RSA PRIVATE KEY-----
      priv key
      -----END RSA PRIVATE KEY-----
    access_token_lifespan: 1h
    authorize_code_lifespan: 1m
    id_token_lifespan: 1h
    refresh_token_lifespan: 90m
    enable_client_debug_messages: false
    enforce_pkce: public_clients_only
    cors:
      endpoints:
        - authorization
        - token
        - revocation
        - introspection
      allowed_origins:
        - https://example.com
      allowed_origins_from_client_redirect_uris: false
    clients:
      - id: myapp
        description: My Application
        secret: 'demosecret'
        sector_identifier: ''
        public: false
        authorization_policy: one_factor
        consent_mode: explicit
        pre_configured_consent_duration: 1w
        audience: []
        scopes:
          - openid
          - groups
          - email
          - profile
        redirect_uris:
          - http://localhost:4000/api/v1/auth/oauth/callback
        grant_types:
          - refresh_token
          - authorization_code
        response_types:
          - code
        response_modes:
          - form_post
          - query
          - fragment
        userinfo_signing_algorithm: none
```
