### ISSUE TITLE
Time indication of video is malfunctioning, showing incorrect duration

### ISSUE THREAD

**Issue by CappiSteijns** [Zibbp/ganymede#258]
Hi!

I'm hosting Ganyemde on Unraid and I've encountered an issue with the time indication of videos. Recently, it always displays that the video lasts only a few seconds or even 0 seconds, preventing me from being able to fast forward or rewind. This issue is hindering my ability to properly navigate through the videos.

I disabled  `- REQUIRE_LOGIN` so you can have a [look](https://ganymede.cappiflex.nl/vods/e9bf59fc-2676-11ee-8993-0242ac130003) for yourself.

This is my docker compose:

```
version: '3.3'
services:
  ganymede-api:
    container_name: ganymede-api
    image: ghcr.io/zibbp/ganymede:latest
    restart: unless-stopped
    environment:
      - TZ=Europe/Amsterdam # Set to your timezone
      - DB_HOST=192.168.68.61
      - DB_PORT=4803
      - DB_USER=XXXX
      - DB_PASS=XXXXXXX
      - DB_NAME=XXXXXXX
      - DB_SSL=disable
      - JWT_SECRET=SECRET
      - JWT_REFRESH_SECRET=SECRET
      - TWITCH_CLIENT_ID=1gfqXXXXXXXXXXXXXXXX7o
      - TWITCH_CLIENT_SECRET=6p66XXXXXXXXXXXXXXXXXXXXXX6j
      - FRONTEND_HOST=https://ganymede.cappiflex.nl
      - COOKIE_DOMAIN=cappiflex.nl
      # OPTIONAL
      # - OAUTH_PROVIDER_URL=
      # - OAUTH_CLIENT_ID=
      # - OAUTH_CLIENT_SECRET=
      # - OAUTH_REDIRECT_URL=http://IP:PORT/api/v1/auth/oauth/callback # Points to the API service
    volumes:
      - /mnt/user/Twitch/ganymede:/vods
      - /mnt/user/appdata/ganymede-api/logs:/logs
      - /mnt/user/appdata/ganymede-api:/data
      # Uncomment below to persist temp files
      - /mnt/user/Twitch/ganymede/temp:/tmp
    ports:
      - 4800:4000
  ganymede-frontend:
    container_name: ganymede-frontend
    image: ghcr.io/zibbp/ganymede-frontend:latest
    restart: unless-stopped
    environment:
      - REQUIRE_LOGIN=false
      - API_URL=https://apiganymede.cappiflex.nl # Points to the API service
      - CDN_URL=https://cdnganymede.cappiflex.nl # Points to the CDN service
      - SHOW_SSO_LOGIN_BUTTON=true # show/hide SSO login button on login page
      - FORCE_SSO_AUTH=false # force SSO auth for all users (bypasses login page and redirects to SSO)
    ports:
      - 4801:3000
  ganymede-db:
    container_name: ganymede-db
    image: postgres:14
    volumes:
      - /mnt/user/appdata/ganymede-db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=XXXXXXXXXXX
      - POSTGRES_USER=XXXXXXXX
      - POSTGRES_DB=XXXXX
    ports:
      - 4803:5432
  ganymede-nginx:
    container_name: ganymede-nginx
    image: nginx
    volumes:
      - /mnt/user/appdata/ganymedenginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /mnt/user/Twitch/ganymede:/mnt/vods
    ports:
      - 4802:8080
```
Any ideas why this is happening and how to fix it?

Thank you! :)
