### ISSUE TITLE
Download hangs when a livestream goes offline

### ISSUE THREAD

**Issue by taeganwarren** [Zibbp/ganymede#37]
Deployed the app on my own server and set up a couple channels for live download. When the channels go live, it does start the writing the stream and continues until the stream goes offline, however it gets stuck at "Closing currently open stream" and never moves on to the Video Convert step. I've attached the log files for a couple streams that I tried to download. Also attached is my docker compose file.

Also, where does the program write the streams to while downloading? The failed downloads are using up some hard drive space and I can not find where the files are at.

[41258272587_6ff09908-32fb-11ed-9ad1-0242ac120003-video.log](https://github.com/Zibbp/ganymede/files/9553476/41258272587_6ff09908-32fb-11ed-9ad1-0242ac120003-video.log)
[47137128733_f59edd85-32f0-11ed-9ad1-0242ac120003-video.log](https://github.com/Zibbp/ganymede/files/9553478/47137128733_f59edd85-32f0-11ed-9ad1-0242ac120003-video.log)

Docker compose file: https://pastebin.com/EqWvxrdp

**Comment by Zibbp** [comment]
Hi,

Everything looks good in the video log files and it appears the stream was downloaded properly. You can try clicking the "restart step" icon for the `video-convert` task in the queue page to force continue.

Is there anything in the container log that may help? If you could, turn on `debug` in `./data/config.json` by setting to `true`. This will require a restart of the container, please ensure no active archive jobs are running before restarting, this action will also **delete** all temporary downloaded stream files. Once restarted it should output more information in the ganymede-api's container logs. If you could provide the container logs near the end of the stream and when it attempts to continue to the next task.

The container logs can be streamed to a file when archiving a live stream using the following command.
```
docker logs -f ganymede-api &> test.log
```

> Also, where does the program write the streams to while downloading? The failed downloads are using up some hard drive space and I can not find where the files are at.


The temporary download location for VOD and stream data is stored in `/tmp` of the container. Restarting the container will flush all data in that directory.

**Comment by taeganwarren** [comment]
Thanks for the reply! I can confirm that manually restarting the `video-convert` task does successfully convert the video and produce the completed .mp4 file. However I needed to manually edit the vod to mark the downloading step as complete. Ganymede then did move on to the `video-move` step and did place the .mp4 in the correct folder on my computer and deleted the temp files, but this step hung as well after finishing, so I then again manually edited the vod to mark the move step as complete and unchecked the `processing` box and I was able to watch the finished vod within Ganymede. One other small thing I noticed, which I assume is due to me manually checking off the tasks, is that once I could watch the finished vod, things like the length (just visually on the thumbnail) and number of viewers were set to 1 instead of their actual values.

Attached is the ganymede-api log file with debug mode turned on as well as the vod download and convert log.

[47140258461_cea3ac86-337f-11ed-83f4-0242ac120003-video-convert.log](https://github.com/Zibbp/ganymede/files/9560085/47140258461_cea3ac86-337f-11ed-83f4-0242ac120003-video-convert.log)
[test.log](https://github.com/Zibbp/ganymede/files/9560083/test.log)
[47140258461_cea3ac86-337f-11ed-83f4-0242ac120003-video.log](https://github.com/Zibbp/ganymede/files/9560084/47140258461_cea3ac86-337f-11ed-83f4-0242ac120003-video.log)

**Comment by taeganwarren** [comment]
Misclicked, did not mean to close the issue. Sorry!

**Comment by Zibbp** [comment]
I noticed you weren't archiving the chat alongside the live video which pointed me in the right direction. I believe I have found the issue. When live stream archiving without the "include chat" option selected, the video task would attempt to terminate the not-running chat downloader. I just published a new release [v1.0.4](https://github.com/Zibbp/ganymede/releases/tag/v1.0.4), that fixes this issue. If you could test it out and report back I would appreciate it.

> One other small thing I noticed, which I assume is due to me manually checking off the tasks, is that once I could watch the finished vod, things like the length (just visually on the thumbnail) and number of viewers were set to 1 instead of their actual values.

Yes, this is due to the step silently failing. The view count will still be 1 as there is not a reliable way to calculate a live stream's view count.

**Comment by taeganwarren** [comment]
I ran a couple live downloads, one with chat and one without. The one without chat worked perfectly, no issues. Went through all the steps and could watch it within ganymede! The one with chat failed with during the chat render step with the error `Failed to create CoreCLR, HRESULT: 0x80004005`. I am running a couple more live downloads to check the results again, but for now the original issue does appear to be fixed! Thank you so much!

**Comment by Zibbp** [comment]
Ganymede utilizes another program for chat rendering called [TwitchDownloader](https://github.com/lay295/TwitchDownloader). It might be beneficial to look if that issues exists over there.

If that render issue continues to persist let me know.

**Comment by taeganwarren** [comment]
All the other downloads I tried without chat worked perfectly. All the ones with chat had the same issue so I'll go ahead and check out that link. Since that's a different issue though I'll go ahead and mark this one as closed. Thank you so much for all the help, I'm really loving Ganymede!

**Comment by feavle** [comment]
Apologies to bump such an old thread but is there a  fix to this issue? Running into this last issue and I get the same error: `TwitchDownloader:Failed to create CoreCLR, HRESULT: 0x80004005`

Here is the debug ganymede-api log:
```
2023-02-10T09:08:55-05:00 DBG restarting task: chat_download for queue id: continue:  
2023-02-10T09:08:55-05:00 DBG starting task chat download for vod f21ba23e-a943-11ed-9a3c-0242ac160003 
2023-02-10T09:08:55-05:00 ERR error running TwitchDownloaderCLI for vod chat download | error=exit status 137
2023-02-10T09:08:55-05:00 ERR error downloading chat | error=exit status 137
```

I have a VPS that has my Google Drive enterprise mounted to it via rclone. The only things that are mapped to it via docker are the vods and tmp folder. Here is my compose:
```
version: "3.3"
services:
  ganymede-api:
    container_name: ganymede-api
    image: ghcr.io/zibbp/ganymede:latest
    restart: unless-stopped
    environment:
      - TZ=America/New_York # Set to your timezone
      - DB_HOST=ganymede-db
      - DB_PORT=5432
      - DB_USER=XXX
      - DB_PASS=XXX
      - DB_NAME=ganymede-prd
      - DB_SSL=disable
      - JWT_SECRET=XXX
      - JWT_REFRESH_SECRET=XXX
      - TWITCH_CLIENT_ID=XXX
      - TWITCH_CLIENT_SECRET=XXX
      - FRONTEND_HOST=http://XXX:4801
      # OPTIONAL
      # - OAUTH_PROVIDER_URL=
      # - OAUTH_CLIENT_ID=
      # - OAUTH_CLIENT_SECRET=
      # - OAUTH_REDIRECT_URL=http://IP:PORT/api/v1/auth/oauth/callback # Points to the API service
    volumes:
      - /home/ganymede/gdrive:/vods
      - /home/ganymede/logs:/logs
      - /home/ganymede/data:/data
      # Uncomment below to persist temp files
      - /home/ganymede/gdrive/tmp:/tmp
    ports:
      - 4800:4000
  ganymede-frontend:
    container_name: ganymede-frontend
    image: ghcr.io/zibbp/ganymede-frontend:latest
    restart: unless-stopped
    environment:
      - API_URL=http://XXX:4800 # Points to the API service
      - CDN_URL=http://XXX:4802 # Points to the CDN service
      - SHOW_SSO_LOGIN_BUTTON=true # show/hide SSO login button on login page
      - FORCE_SSO_AUTH=false # force SSO auth for all users (bypasses login page and redirects to SSO)
      - REQUIRE_LOGIN=true # require login to view videos
    ports:
      - 4801:3000
  ganymede-db:
    container_name: ganymede-db
    image: postgres:14
    volumes:
      - /home/ganymede/database:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=PASSWORD
      - POSTGRES_USER=ganymede
      - POSTGRES_DB=ganymede-prd
    ports:
      - 4803:5432
  ganymede-nginx:
    container_name: ganymede-nginx
    image: nginx
    volumes:
      - /home/ganymede/nginx.conf:/etc/nginx/nginx.conf:ro
      - /home/ganymede/gdrive:/mnt/vods
    ports:
      - 4802:8080
```

Anything else I can add to help debug?
