### ISSUE TITLE
Application error on Settings Page

### ISSUE THREAD

**Issue by NothingTV** [Zibbp/ganymede#429]
Hi there!
I just revived my ganymede instance and added the temporal container and right after that I can't access the settings page anymore, I get the error `Application error: a client-side exception has occurred (see the browser console for more information).`. In console I see two `TypeError: eW is null` messages. I don't see anything else, is there a way to debug this further?

Regards

**Comment by Zibbp** [comment]
Any logs in the API container when you access the settings page? If you restart the API container and watch the logs do you see any errors? and what is the build date that gets printed?

**Comment by NothingTV** [comment]
Absolutely no logs in the api container about this, it happened right after I added the temporal container. It also just created another task for a live channel which was offline for about 1 min (now with another title tho) and instead of using the old task or cancelling the old task, there are now two tasks for the same livestream.

**Comment by NothingTV** [comment]
Mostly yes, here is my `docker-compose.yml`:
```
services:
  ganymede-api:
    container_name: ganymede-api
    image: ghcr.io/zibbp/ganymede:latest
    restart: unless-stopped
    depends_on:
      - ganymede-temporal
    environment:
      - TZ=Europe/Berlin
      - DB_HOST=ganymede-db
      - DB_PORT=5432
      - DB_USER=ganymede
      - DB_PASS=XXXX
      - DB_NAME=ganymede
      - DB_SSL=disable
      - JWT_SECRET=XXXX
      - JWT_REFRESH_SECRET=XXXX
      - TWITCH_CLIENT_ID=XXXX
      - TWITCH_CLIENT_SECRET=XXXX
      - FRONTEND_HOST=https://front-end.XXXX
      - COOKIE_DOMAIN=.XXXX
      - NUXT_PUBLIC_API_URL=https://api.XXXX
      - NUXT_PUBLIC_CDN_URL=https://cdn.XXXX
      # OPTIONAL
      # - OAUTH_PROVIDER_URL=
      # - OAUTH_CLIENT_ID=
      # - OAUTH_CLIENT_SECRET=
      # - OAUTH_REDIRECT_URL=https://XXXX/api/v1/auth/oauth/callback # Points to the API service
      - TEMPORAL_URL=ganymede-temporal:7233
      # WORKER
      - MAX_CHAT_DOWNLOAD_EXECUTIONS=5
      - MAX_CHAT_RENDER_EXECUTIONS=3
      - MAX_VIDEO_DOWNLOAD_EXECUTIONS=5
      - MAX_VIDEO_CONVERT_EXECUTIONS=3
    volumes:
      - /storage/vods:/vods
      - /root/ganymede/logs:/logs
      - /root/ganymede/data:/data
      - /tmp/vods:/tmp
    ports:
      - 4800:4000
  ganymede-frontend:
    container_name: ganymede-frontend
    image: ghcr.io/zibbp/ganymede-frontend:latest
    restart: unless-stopped
    environment:
      - API_URL=https://api.XXXX
      - CDN_URL=https://cdn.XXXX
      - SHOW_SSO_LOGIN_BUTTON=false
      - FORCE_SSO_AUTH=false
      - REQUIRE_LOGIN=false
    ports:
      - 4801:3000
  ganymede-temporal:
    image: temporalio/auto-setup:latest
    container_name: ganymede-temporal
    depends_on:
      - ganymede-db
    environment:
      - DB=postgresql
      - DB_PORT=5432
      - POSTGRES_USER=ganymede
      - POSTGRES_PWD=XXXX
      - POSTGRES_SEEDS=ganymede-db
    ports:
      - 7233:7233
  ganymede-temporal-ui:
    image: temporalio/ui:latest
    container_name: ganymede-temporal-ui
    depends_on:
      - ganymede-temporal
    environment:
      - TEMPORAL_ADDRESS=ganymede-temporal:7233
    ports:
      - 8233:8080
  ganymede-db:
    container_name: ganymede-db
    image: postgres:14
    volumes:
      - ./ganymede-db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=XXXX
      - POSTGRES_USER=ganymede
      - POSTGRES_DB=ganymede
    ports:
      - 4803:5432
  ganymede-nginx:
    container_name: ganymede-nginx
    image: nginx
    volumes:
      - /root/ganymede/nginx.conf:/etc/nginx/nginx.conf:ro
      - /storage/vods:/mnt/vods
    ports:
      - 4802:8080
```
