### ISSUE TITLE
"Chat Download" never stops

### ISSUE THREAD

**Issue by CappiSteijns** [Zibbp/ganymede#450]
I'm not sure what is happening, but the "chat download" never stop, resulting in errors. Some downloads are successfully recorded and moved, while others are not. See the pictures and logs below.

![image](https://github.com/Zibbp/ganymede/assets/84481241/674dbd1d-9373-4f6f-98e5-666a73f8a5ab)
![image](https://github.com/Zibbp/ganymede/assets/84481241/1a8559ce-0907-40ac-834b-7d7052956bc7)
![image](https://github.com/Zibbp/ganymede/assets/84481241/5ba5015f-5118-4e06-9fd1-b00c890dcd35)
![image](https://github.com/Zibbp/ganymede/assets/84481241/b06a1a2b-fb03-442d-8234-3fa63eb8c814)

The logs in ganymede itself;
"Video Download" log:
![image](https://github.com/Zibbp/ganymede/assets/84481241/ef2a6ec2-7a4e-46f7-a1cd-f1e8e8c97236)

"Chat Download" log:
![image](https://github.com/Zibbp/ganymede/assets/84481241/f80c437b-a84e-4efb-9be5-2815bb8d48f4)

[ganymede-api-2024-06-13T15-46-06.log](https://github.com/user-attachments/files/15823478/ganymede-api-2024-06-13T15-46-06.log)
[ganymede-temporal-2024-06-13T15-47-47.log](https://github.com/user-attachments/files/15823493/ganymede-temporal-2024-06-13T15-47-47.log)

If you need more logs let me know please :)

EDIT: added docker compose

```
services:
  ganymede-api:
    container_name: ganymede-api
    image: ghcr.io/zibbp/ganymede:latest
    restart: unless-stopped
    environment:
      - TZ=Europe/Amsterdam # Set to your timezone
      - DB_HOST=192.168.68.61
      - DB_PORT=4803
      - DB_USER=ganymede
      - DB_PASS=####
      - DB_NAME=ganymede-prd
      - DB_SSL=disable
      - JWT_SECRET=SECRET
      - JWT_REFRESH_SECRET=SECRET
      - TWITCH_CLIENT_ID=############xjm7o
      - TWITCH_CLIENT_SECRET=6################or6j
      - FRONTEND_HOST=https://###########.nl
      - COOKIE_DOMAIN=########.nl
      # OPTIONAL
      # - OAUTH_PROVIDER_URL=
      # - OAUTH_CLIENT_ID=
      # - OAUTH_CLIENT_SECRET=
      # - OAUTH_REDIRECT_URL=http://IP:PORT/api/v1/auth/oauth/callback # Points to the API service
      # Volgende heb ik toegevoegd voor UPDATE 2.0.0
      - TEMPORAL_URL=ganymede-temporal:7233
      # WORKER
      - MAX_CHAT_DOWNLOAD_EXECUTIONS=5
      - MAX_CHAT_RENDER_EXECUTIONS=3
      - MAX_VIDEO_DOWNLOAD_EXECUTIONS=5
      - MAX_VIDEO_CONVERT_EXECUTIONS=3      
    volumes:
      - /mnt/user/Twitch/ganymede:/vods
      - /mnt/user/appdata/ganymede-api/logs:/logs
      - /mnt/user/appdata/ganymede-api:/data
      # Uncomment below to persist temp files
      - /mnt/user/Twitch/ganymede/temp:/tmp
    ports:
      - 4800:4000
  ganymede-frontend:
    container_name: ganymede-frontend
    image: ghcr.io/zibbp/ganymede-frontend:latest
    restart: unless-stopped
    environment:
      - REQUIRE_LOGIN=true
      - API_URL=https://apiganymede.cappiflex.nl # Points to the API service
      - CDN_URL=https://cdnganymede.cappiflex.nl # Points to the CDN service
      - SHOW_SSO_LOGIN_BUTTON=true # show/hide SSO login button on login page
      - FORCE_SSO_AUTH=false # force SSO auth for all users (bypasses login page and redirects to SSO)
    ports:
      - 4801:3000
  ganymede-db:
    container_name: ganymede-db
    image: postgres:14
    volumes:
      - /mnt/user/appdata/ganymede-db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=#######
      - POSTGRES_USER=ganymede
      - POSTGRES_DB=ganymede-prd
    ports:
      - 4803:5432
  ganymede-nginx:
    container_name: ganymede-nginx
    image: nginx
    volumes:
      - /mnt/user/appdata/ganymedenginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /mnt/user/Twitch/ganymede:/mnt/vods
    ports:
      - 4802:8080
  ganymede-temporal:
    image: temporalio/auto-setup:1.23
    container_name: ganymede-temporal
    depends_on:
      - ganymede-db
    environment:
      - DB=postgres12 # this tells temporal to use postgres (not the db name)
      - DB_PORT=5432
      - POSTGRES_USER=ganymede
      - POSTGRES_PWD=#####
      - POSTGRES_SEEDS=ganymede-db # name of the db service
    ports:
      - 7233:7233
```
