### ISSUE TITLE
Application error: a client-side exception has occurred (see the browser console for more information).

### ISSUE THREAD

**Issue by CappiSteijns** [Zibbp/ganymede#476]
SInce a short time I can't access the settings (/admin/settings) page anymore and get the following error:

![image](https://github.com/user-attachments/assets/108fcb40-2053-4bcf-8d5a-f60c3df4214f)

When checking with the console I get the following:

![image](https://github.com/user-attachments/assets/220993d3-dcac-4739-bd87-c7d8fed51557)

I get this error on locall and on reverse proxy.

```
services:
  ganymede-api:
    container_name: ganymede-api
    image: ghcr.io/zibbp/ganymede:latest
    restart: unless-stopped
    environment:
      - TZ=Europe/Amsterdam # Set to your timezone
      - DB_HOST=192.168.68.61
      - DB_PORT=4803
      - DB_USER=ganymede
      - DB_PASS=###########2
      - DB_NAME=ganymede-prd
      - DB_SSL=disable
      - JWT_SECRET=SECRET
      - JWT_REFRESH_SECRET=SECRET
      - TWITCH_CLIENT_ID=#############o
      - TWITCH_CLIENT_SECRET=###############or6j
      - FRONTEND_HOST=http://192.168.68.61:4801
      # OPTIONAL
      # - OAUTH_PROVIDER_URL=
      # - OAUTH_CLIENT_ID=
      # - OAUTH_CLIENT_SECRET=
      # - OAUTH_REDIRECT_URL=http://IP:PORT/api/v1/auth/oauth/callback # Points to the API service
      # Volgende heb ik toegevoegd voor UPDATE 2.0.0
      - TEMPORAL_URL=ganymede-temporal:7233
      # WORKER
      - MAX_CHAT_DOWNLOAD_EXECUTIONS=5
      - MAX_CHAT_RENDER_EXECUTIONS=1
      - MAX_VIDEO_DOWNLOAD_EXECUTIONS=5
      - MAX_VIDEO_CONVERT_EXECUTIONS=1      
    volumes:
      - /mnt/user/Twitch/ganymede:/vods
      - /mnt/user/appdata/ganymede-api/logs:/logs
      - /mnt/user/appdata/ganymede-api:/data
      # Uncomment below to persist temp files
      - /mnt/user/Twitch/ganymede/temp:/tmp
    ports:
      - 4800:4000
  ganymede-frontend:
    container_name: ganymede-frontend
    image: ghcr.io/zibbp/ganymede-frontend:latest
    restart: unless-stopped
    environment:
      - REQUIRE_LOGIN=true
      - API_URL=http://192.168.68.61:4800 # Points to the API service
      - CDN_URL=http://192.168.68.61:4802 # Points to the CDN service
      - SHOW_SSO_LOGIN_BUTTON=true # show/hide SSO login button on login page
      - FORCE_SSO_AUTH=false # force SSO auth for all users (bypasses login page and redirects to SSO)
    ports:
      - 4801:3000
  ganymede-db:
    container_name: ganymede-db
    image: postgres:14
    volumes:
      - /mnt/user/appdata/ganymede-db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=##########2
      - POSTGRES_USER=ganymede
      - POSTGRES_DB=ganymede-prd
    ports:
      - 4803:5432
  ganymede-nginx:
    container_name: ganymede-nginx
    image: nginx
    volumes:
      - /mnt/user/appdata/ganymedenginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /mnt/user/Twitch/ganymede:/mnt/vods
    ports:
      - 4802:8080
  ganymede-temporal:
    image: temporalio/auto-setup:1.23
    container_name: ganymede-temporal
    depends_on:
      - ganymede-db
    environment:
      - DB=postgres12 # this tells temporal to use postgres (not the db name)
      - DB_PORT=5432
      - POSTGRES_USER=ganymede
      - POSTGRES_PWD=################2
      - POSTGRES_SEEDS=ganymede-db # name of the db service
    ports:
      - 7233:7233
  ganymede-temporal-ui:
    image: temporalio/ui:latest
    container_name: ganymede-temporal-ui
    depends_on:
      - ganymede-temporal
    environment:
      - TEMPORAL_ADDRESS=ganymede-temporal:7233
    ports:
      - 8233:8080
```

Hope some of this helps.
