### ISSUE TITLE
Can't login or register

### ISSUE THREAD

**Issue by olveirap** [Zibbp/ganymede#67]
Hi! I´m trying to use ganymede but can´t seem to login or register. I've checked both the console of my browser and the logs of every image and can't find any error. Can I have some pointers on where to look? Thanks in advance!

**Comment by Zibbp** [comment]
Hi,
Can you double check to ensure the `FRONTEND_HOST` env var for the API and `API_URL` env var for the frontend are properly set? While logging in, take a look at the network tab and see if any requests are being made.

**Comment by olveirap** [comment]
Oh I forgot to set those. Now I can see the request being made in the network tab and in the console log I'm hit with:

`Access to XMLHttpRequest at 'http://192.168.1.52:4800/api/v1/auth/login' from origin 'http://192.168.1.52:4801' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

As you can probably notice I'm trying to access it from the same computer it's running.

**Comment by Zibbp** [comment]
CORS issue is probably related to the API container `FRONTEND_HOST` env var. Ensure it is set to `http://192.168.1.52:4801`.

**Comment by olveirap** [comment]
I had it wrongly configured to the port 4800, but correcting that didn't fix the issue, double checked printing the variable inside the container that it was correctly set. Same error on console.

**Comment by Zibbp** [comment]
To confirm, your API and Frontend docker compose env vars are as follows:

 - API Container `docker-compose.yml` env var
   - `FRONTEND_HOST=http://192.168.1.52:4801`
 - Frontend Container `docker-compose.yml` env var
   -  `API_URL=http://192.168.1.52:4800`

I'm assuming you are using the default ports of 4800 for the API and 4801 for the frontend correct? Is this a new installation or updating? If this still does not work, please paste a redacted version of your `docker-compose.yml` removing any sensitive information.

**Comment by olveirap** [comment]
Both are set as you state in the `docker-compose.yml` file, however, when echoing `$API_URL` on the frontend container it comes up empty. 

This is a new installation, I'm just starting my self-hosting path and this is one of the first docker applications I'm setting up. 

Here is my `docker-compose.yml`:

```
version: '3.3'
services:
  ganymede-api:
    container_name: ganymede-api
    image: ghcr.io/zibbp/ganymede:latest
    restart: unless-stopped
    environment:
      - TZ=America/Argentina/Buenos_Aires # Set to your timezone
      - DB_HOST=ganymede-db
      - DB_PORT=5432
      - DB_USER=ganymede
      - DB_PASS=PASSWORD
      - DB_NAME=ganymede-prd
      - DB_SSL=disable
      - JWT_SECRET=SECRET
      - JWT_REFRESH_SECRET=SECRET
      - TWITCH_CLIENT_ID=<REDACTED>
      - TWITCH_CLIENT_SECRET=<REDACTED>
      - FRONTEND_HOST=http://192.168.1.52:4801
      # OPTIONAL
      # - OAUTH_PROVIDER_URL=
      # - OAUTH_CLIENT_ID=
      # - OAUTH_CLIENT_SECRET=
      # - OAUTH_REDIRECT_URL=http://IP:PORT/api/v1/auth/oauth/callback # Points to the API service
    volumes:
      - ../../docker_data/ganymede/vods:/vods
      - ../../docker_data/ganymede/logs:/logs
      - ../../docker_data/ganymede/data:/data
      # Uncomment below to persist temp files
      #- ./tmp:/tmp
    ports:
      - 4800:4000
  ganymede-frontend:
    container_name: ganymede-frontend
    image: ghcr.io/zibbp/ganymede-frontend:latest
    restart: unless-stopped
    environment:
      - API_URL=http://192.168.1.52:4800 # Points to the API service
      - CDN_URL=http://192.168.1.52:4802 # Points to the CDN service
      - SHOW_SSO_LOGIN_BUTTON=true # show/hide SSO login button on login page
      - FORCE_SSO_AUTH=false # force SSO auth for all users (bypasses login page and redirects to SSO)
    ports:
      - 4801:3000
  ganymede-db:
    container_name: ganymede-db
    image: postgres:14
    volumes:
      - ./ganymede-db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=PASSWORD
      - POSTGRES_USER=ganymede
      - POSTGRES_DB=ganymede-prd
    ports:
      - 4803:5432
  ganymede-nginx:
    container_name: ganymede-nginx
    image: nginx
    volumes:
      - ~/Projects/ganymede/nginx.conf:/etc/nginx/nginx.conf:ro
      - ../../docker_data/ganymede/vods:/mnt/vods
    ports:
      - 4802:8080
```
